
const DomainConstant = {
  GET_DOMAIN_LIST: '[DOMAIN] GET_DOMAIN_LIST',
  GET_DOMAIN_LIST_SUCCESS: '[DOMAIN] GET_DOMAIN_LIST_SUCCESS',
  GET_DOMAIN_LIST_FAILED: '[DOMAIN] GET_DOMAIN_LIST_FAILED',

  GET_DOMAIN_DETAIL: '[DOMAIN] GET_DOMAIN_DETAIL',
  GET_DOMAIN_DETAIL_SUCCESS: '[DOMAIN] GET_DOMAIN_DETAIL_SUCCESS',
  GET_DOMAIN_DETAIL_FAILED: '[DOMAIN] GET_DOMAIN_DETAIL_FAILED',

  GET_ISSUE: '[DOMAIN] GET_ISSUE',
  GET_ISSUE_SUCCESS: '[DOMAIN] GET_ISSUE_SUCCESS',
  GET_ISSUE_FAILED: '[DOMAIN] GET_ISSUE_FAILED',

  SET_ISSUE_LOADING: '[DOMAIN] SET_ISSUE_LOADING',
};
export default DomainConstant;